kind: Job
apiVersion: batch/v1
metadata:
  name: cmmd
spec:
  template:
    spec:
      containers:
        - name: cmmd
          image: "rogelioandrade/theano_setup:v4"
          workingDir: /mnt/azure/cmmd/python
          command: ["bash","./run_cmmd.sh"]
          volumeMounts:
          -  name: azure
             mountPath: /mnt/azure    
      nodeSelector:
        nvidia1/gpu: "true"
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule" 
      volumes:
        - name: azure
          persistentVolumeClaim:
            claimName: azurefile
      restartPolicy: OnFailure
  backoffLimit: 0
